### PR TITLE
Manual zero calibration

### LINKED ISSUE #13: After calibration, incorrect data
After applying the kolibrovochny sketch. My sensor started showing values in ppm like this: 12002000020

### PR DESCRIPTION
**Pull request by Beanow**
Fixes #13
Closes #14 (supersedes it)

Some choices I would like to get your thoughts on @RobTillaart:

- The `AGS02MA::ZeroCalibration` struct. I think is useful because it's fairly common to need both values, and it would avoid having to read the register twice, at the cost of 2 extra bytes allocated when you don't need both.
But it's a bit different from existing functions. Like `getSensorVersion` and `getSensorDate`, could have been one struct too.
- I've updated the existing example sketch, and added one for manual zero calibration. They are much more verbose than before, including a bunch of hints and PPB output. And I wonder... is it too verbose? Do all the `Serial.print` pollute the actual example code? Or is this a good idea because it provides more utility for calibrating that way? :thinking:

<details><summary>Example output of the updated <code>examples/AGS02MA_calibrate</code>:</summary>

```
/home/beanow/Arduino/libraries/AGS02MA/examples/AGS02MA_calibrate/AGS02MA_calibrate.ino
AGS02MA_LIB_VERSION: 0.2.0

WARMUP:		1
INTERVAL:	3000
BEGIN:		1
VERSION:	118
MODE:		1	0

Place the device outside in open air for 1 minute(s).
Make sure your device has warmed up sufficiently for the best results.
The PPB values should be stable (may include noise) not constantly decreasing.

[PRE ]	PPB:	3	0	0
[PRE ]	PPB:	3	0	0
[PRE ]	PPB:	3	0	0
[PRE ]	PPB:	3	0	0
[PRE ]	PPB:	3	0	0
[PRE ]	PPB:	3	0	0
[PRE ]	PPB:	3	0	0
[PRE ]	PPB:	3	0	0
[PRE ]	PPB:	3	0	0
[PRE ]	PPB:	3	0	0
[PRE ]	PPB:	2	0	0
[PRE ]	PPB:	2	0	0
[PRE ]	PPB:	3	0	0
[PRE ]	PPB:	3	0	0
[PRE ]	PPB:	3	0	0
[PRE ]	PPB:	3	0	0
[PRE ]	PPB:	3	0	0
[PRE ]	PPB:	3	0	0
[PRE ]	PPB:	3	0	0
[PRE ]	PPB:	3	0	0

About to perform calibration now. Your previous calibration data was:
Status:	12
Value:	1738

CALIB:	1

Calibration done, your new calibration data is:
Status:	12
Value:	1762

Showing what PPB values look like post calibration.
NOTICE: v118 sensors are known to give different results after powering off!
You may need to manually set your calibration value every time power was lost.

[POST]	PPB:	3	0	0
[POST]	PPB:	5	0	0
[POST]	PPB:	5	0	0
[POST]	PPB:	5	0	0
[POST]	PPB:	6	0	0
[POST]	PPB:	6	0	0
[POST]	PPB:	6	0	0
[POST]	PPB:	6	0	0
[POST]	PPB:	6	0	0
[POST]	PPB:	6	0	0
[POST]	PPB:	6	0	0
[POST]	PPB:	6	0	0
[POST]	PPB:	6	0	0
[POST]	PPB:	6	0	0
[POST]	PPB:	6	0	0
[POST]	PPB:	6	0	0
[POST]	PPB:	6	0	0
```

</details>

<details><summary>Example output of the new <code>examples/AGS02MA_calibrate_manual</code>:</summary>

```
/home/beanow/Arduino/libraries/AGS02MA/examples/AGS02MA_calibrate_manual/AGS02MA_calibrate_manual.ino
AGS02MA_LIB_VERSION: 0.2.0

READS:		10
INTERVAL:	3000
BEGIN:		1
VERSION:	118
MODE:		1	0

Your initial zero calibration is:
Status:	12
Value:	1762
NOTICE: v118 sensors are known to give different results after powering off!
You may need to manually set your calibration value every time power was lost.

Showing sample data before changing.
PPB:	7	0	0
PPB:	7	0	0
PPB:	8	0	0
PPB:	16	0	0
PPB:	8	0	0
PPB:	8	0	0
PPB:	8	0	0
PPB:	8	0	0
PPB:	8	0	0
PPB:	8	0	0

Manually setting zero calibration:
CALIB:	1
Status:	12
Value:	700

Showing sample data.
PPB:	0	0	0
PPB:	0	0	0
PPB:	0	0	0
PPB:	0	0	0
PPB:	0	0	0
PPB:	0	0	0
PPB:	0	0	0
PPB:	0	0	0
PPB:	0	0	0
PPB:	0	0	0

Restoring initial zero calibration:
CALIB:	1
Status:	12
Value:	1762

PPB:	4	0	0
PPB:	4	0	0
PPB:	4	0	0
PPB:	4	0	0
PPB:	5	0	0
PPB:	5	0	0
PPB:	5	0	0
PPB:	5	0	0
PPB:	4	0	0
PPB:	4	0	0
PPB:	4	0	0
PPB:	4	0	0
PPB:	5	0	0
PPB:	5	0	0
PPB:	5	0	0
PPB:	5	0	0
PPB:	5	0	0
PPB:	5	0	0
PPB:	5	0	0
PPB:	5	0	0
PPB:	5	0	0
```

</details>

### CODE REVIEW

File: AGS02MA.cpp [hunk 1]
```diff
@@ -205,17 +205,34 @@ uint32_t AGS02MA::readUGM3()
...
+
+bool AGS02MA::manualZeroCalibration(uint16_t value)
 {
   _buffer[0] = 0x00;
   _buffer[1] = 0x0C;
-  _buffer[2] = 0xFF;
-  _buffer[3] = 0xF3;
-  _buffer[4] = 0xFC;
+  _buffer[2] = (uint8_t) (value >> 8);
+  _buffer[3] = (uint8_t) value;
```
Comment (RobTillaart) [inline AGS02MA.cpp:214]: (uint8_t) (value & 0x00FF)  is more explicit

File: AGS02MA.cpp [hunk 2]
```diff
@@ -301,6 +318,15 @@ bool AGS02MA::_writeRegister(uint8_t reg)
   return (_error == 0);
 }
 
+uint16_t AGS02MA::_dataMSB(uint8_t * buf)
```
Comment (RobTillaart) [inline AGS02MA.cpp:321]: unclear from function name it is a get

File: AGS02MA.cpp [hunk 3]
```diff
@@ -205,17 +205,34 @@ uint32_t AGS02MA::readUGM3()
...
+  {
+    _error = AGS02MA_OK;
+    zc.status = _dataMSB(_buffer);
+    zc.value = _dataLSB(_buffer);
+    if (_CRC8(_buffer, 5) != 0)
+    {
+      _error = AGS02MA_ERROR_CRC;
+    }
+  }
+  return zc;
```
Comment (RobTillaart) [inline AGS02MA.cpp:232]: if readRegister() fails ZC is not initialized and can have any value (as it is a local var from a function)
Furthermore the _error should be set - although yes it is set in _readregister()

So the user should always check _error to be sure that  ZC contains meaningful data. 
Should we extend the ZC with a "bool valid" to make it a bit easier?

If there is a CRC error, can we trust the ZC.status and ZC.value?

```cpp
AGS02MA::ZeroCalibration AGS02MA::getZeroCalibration() {
  AGS02MA::ZeroCalibration zc = {0, 0};    // or -1, -1 ?
  if (_readRegister(AGS02MA_CALIBRATION) == false)
  {
    _error = AGS02MA_ERROR_CALIBRATION ...
  }
  else if (_CRC8(_buffer, 5) != 0)
  {
    _error = AGS02MA_ERROR_CRC;
  }
  else
  {
    _error = AGS02MA_OK;
    zc.status = _dataMSB(_buffer);    // as _buffer is a local var I think it doesn't need to be a parameter ...
    zc.value = _dataLSB(_buffer);
  }
  return zc;
}
```

File: AGS02MA.cpp [hunk 4]
```diff
@@ -301,6 +318,15 @@ bool AGS02MA::_writeRegister(uint8_t reg)
   return (_error == 0);
 }
 
+uint16_t AGS02MA::_dataMSB(uint8_t * buf)
+{
+  return (buf[0] << 8) + buf[1];
+}
+
+uint16_t AGS02MA::_dataLSB(uint8_t * buf)
```
Comment (RobTillaart) [inline AGS02MA.cpp:326]: idem

File: AGS02MA.h [hunk 5]
```diff
@@ -28,6 +28,11 @@
 class AGS02MA
 {
 public:
+  struct ZeroCalibration {
```
Comment (RobTillaart) [inline AGS02MA.h:31]: should it be called ZeroCalibrationData  to prevent confusion with the function with same name?
(no showstopper ;)

File: examples/AGS02MA_calibrate/AGS02MA_calibrate.ino [hunk 6]
```diff
@@ -1,59 +1,133 @@
...
 AGS02MA AGS(26);
 
 
 void setup()
 {
+  // ESP devices typically mis the first serial log lines after flashing.
+  // Delay somewhat to include all output.
+  delay(1000);
+
   Serial.begin(115200);
```
Comment (RobTillaart) [inline examples/AGS02MA_calibrate/AGS02MA_calibrate.ino:29]: Some platforms need a line ```while(!Serial);```  - think the NANO33 (mbed) needs but people can add that theselves.
(no real issue)

File: examples/AGS02MA_calibrate/AGS02MA_calibrate.ino [hunk 7]
```diff
@@ -1,59 +1,133 @@
 //
```
Comment (RobTillaart) [inline examples/AGS02MA_calibrate/AGS02MA_calibrate.ino:1]: Looks good! 👍

File: examples/AGS02MA_calibrate_manual/AGS02MA_calibrate_manual.ino [hunk 8]
```diff
@@ -0,0 +1,136 @@
+//
```
Comment (RobTillaart) [inline examples/AGS02MA_calibrate_manual/AGS02MA_calibrate_manual.ino:1]: Looks good!

**Comment by RobTillaart** [comment]
See comments above.

File: examples/AGS02MA_calibrate_manual/AGS02MA_calibrate_manual.ino [hunk 9]
```diff
@@ -0,0 +1,136 @@
...
+#define ZC_VALUE 700
+
+#define READS 10
+#define INTERVAL 3000
+
+
+AGS02MA AGS(26);
+
+AGS02MA::ZeroCalibration initialValue;
+u_int8_t version;
```
Comment (RobTillaart) [inline examples/AGS02MA_calibrate_manual/AGS02MA_calibrate_manual.ino:22]: should be uint8_t

File: AGS02MA.h (hunk 5 above)
Comment (Beanow) [reply AGS02MA.h:31]: > Do we have information about the different values status can have ? what they mean etc?
Need to mention "warning: this is experimental / under investigation" ?

Not really. Only these observations so far.

```
0000 1100 | 0x0C | 12
0000 1101 | 0x0D | 13
0111 1101 | 0x7D | 125
```

- It looks like a bitmask.
- `12` is the value v117 seems to have normally. v118 has this *immediately* after setting calibration.
- `13` I've only seen in your v117 dumps. I don't know under which conditions. I've not seen it on v118.
- `125` I've only seen on v118, after power-cycling it. Typically this means you get different PPB values from `12`!

File: AGS02MA.cpp (hunk 3 above)
Comment (Beanow) [reply AGS02MA.cpp:232]: All good points. Should we change the function signature to be similar to my register dumping example?

```cpp
int|bool getZeroCalibrationData(ZeroCalibrationData &data);
```

Such that return value makes errors explicit, having to initialize the struct yourself though.

File: AGS02MA.cpp (hunk 2 above)
Comment (Beanow) [reply AGS02MA.cpp]: True, `_buffer` is local. Though I was mimicking the `_CRC8` method here, allowing any arbitrary buffer to be used.
No huge preferences though, it's such a small function body it might as well be inlined.

File: examples/AGS02MA_calibrate_manual/AGS02MA_calibrate_manual.ino (hunk 9 above)
Comment (Beanow) [reply examples/AGS02MA_calibrate_manual/AGS02MA_calibrate_manual.ino]: Ha, oops. Fixed that.

File: AGS02MA.h (hunk 5 above)
Comment (Beanow) [reply AGS02MA.h]: With mentioning a warning, do you mean adding something like this?

```cpp
  struct ZeroCalibrationData
  {
    /**
     * Warning, the exact meaning of this status is not fully undocumented.
     * It seems like it's a bitmask:
     * 0000 1100 | 0x0C | 12  | Typical value
     * 0000 1101 | 0x0D | 13  | Sometimes seen on v117
     * 0111 1101 | 0x7D | 125 | Seen on v118, after power-off (gives different data than "12")
     */
    uint16_t status;
    uint16_t value;
  };
```

File: AGS02MA.cpp (hunk 2 above)
Comment (Beanow) [reply AGS02MA.cpp]: Renamed and using local variable.

File: AGS02MA.cpp (hunk 4 above)
Comment (Beanow) [reply AGS02MA.cpp]: Renamed and using local variable.

File: AGS02MA.cpp (hunk 1 above)
Comment (Beanow) [reply AGS02MA.cpp]: I'm not sure if any/all of these explicit casts / masks would get compiler optimized away or cost additional cycles.
But I think explicit is better too, so using your suggested mask.

File: examples/AGS02MA_calibrate_manual/AGS02MA_calibrate_manual.ino (hunk 9 above)
Comment (Beanow) [reply examples/AGS02MA_calibrate_manual/AGS02MA_calibrate_manual.ino]: Weird how `u_int8_t` even compiled for me. I'm guessing the arduino-esp32 fork includes it somehow while not being in the base Arduino. Because the CI test does fail to compile on that. :shrug:

Comment (Beanow) [reply examples/AGS02MA_calibrate_manual/AGS02MA_calibrate_manual.ino]: `F12` to the rescue, indeed the culprit was this :eyes:
`~/.arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/gcc8_4_0-esp-2021r2/xtensa-esp32-elf/sys-include/sys/types.h`

File: AGS02MA.cpp (hunk 3 above)
Comment (RobTillaart) [reply AGS02MA.cpp:231]: Think that is better
(I know a lot is a matter of taste,  I try to think how less experienced people can work with it, think this latter is the better one)

File: AGS02MA.h [hunk 10]
```diff
@@ -99,6 +114,8 @@ class AGS02MA
   uint8_t  _status        = 0;
   uint8_t  _buffer[5];
 
+  uint16_t _getDataMSB();
```
Comment (RobTillaart) [inline AGS02MA.h:117]: Do these function names match the .cpp file ?

Comment (RobTillaart) [reply AGS02MA.h:117]: yes

File: README.md [hunk 11]
```diff
@@ -170,6 +170,9 @@ Typical value should be between 0.01 .. 999.99
 
 - **bool zeroCalibration()** to be called after at least 5 minutes in fresh air.
 See example sketch.
+- **bool manualZeroCalibration(uint16_t value)** for v118 sensors, set the zero calibration value manually.
```
Comment (RobTillaart) [inline README.md:173]: .h file says 
bool                manualZeroCalibration(uint16_t value = 0);
need to add default value to documentation. 

maybe add a 117 comment?

**Comment by RobTillaart** [comment]
Think your PR is a major step forward for the library. We're closing in on a merge. 
Note I squash all commits to keep history short, but I keep the individual commit texts (that make sense)

Can you update the version in the library.json and library.properties files too.

File: AGS02MA.cpp (hunk 3 above)
Comment (Beanow) [reply AGS02MA.cpp:231]: Well even experienced people can easily make the mistake of not error handling if it's not very explicit.
Case in point, both updated examples don't handle read calibration data errors atm :joy:
I'll go with the bool return value to match other methods, and update accordingly.

File: README.md (hunk 11 above)
Comment (Beanow) [reply README.md]: Mirrored the comment I had in the source file.

File: AGS02MA.h (hunk 5 above)
Comment (Beanow) [reply AGS02MA.h]: I've included this warning in source now. Assuming that's what you meant.

File: AGS02MA.cpp (hunk 3 above)
Comment (Beanow) [reply AGS02MA.cpp]: Now with 80% more error and 120% more handling!

**Comment by RobTillaart** [comment]
FYI - busy with other things - might take a few days.

**Review by RobTillaart — APPROVED** [review]

**Comment by RobTillaart** [comment]
@Beanow 
Thanks for the work you did on this PR.
